"""
Magic Story Maker
=================

An AI-powered storytelling application for children aged 3-10.

The child uploads a picture and the application:

    1. Looks at the picture          -> image2text()
    2. Imagines a story about it     -> text2story()
    3. Reads the story out loud      -> text2audio()

Everything is orchestrated by main() and presented through Streamlit.

Pre-trained models (Hugging Face Transformers pipelines):
    image-to-text   : Salesforce/blip-image-captioning-large
    text-generation : LiquidAI/LFM2-1.2B
    text-to-speech  : facebook/mms-tts-eng
"""

import html
import io
import os
import wave

import numpy as np
import streamlit as st
import torch
from PIL import Image, UnidentifiedImageError
from transformers import pipeline

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# The three models selected during the notebook experimentation stage.
IMAGE_MODEL = "Salesforce/blip-image-captioning-large"
STORY_MODEL = "LiquidAI/LFM2-1.2B"
AUDIO_MODEL = "facebook/mms-tts-eng"

# Limits used by the image and story stages.
MAX_CAPTION_TOKENS = 50
MAX_STORY_TOKENS = 180

ACCEPTED_IMAGE_TYPES = ["jpg", "jpeg", "png", "webp"]


# ---------------------------------------------------------------------------
# 1. Model loading
# ---------------------------------------------------------------------------

def get_hf_token():
    """
    Return the Hugging Face access token if one has been configured.

    The token is read from Streamlit secrets or from an environment variable,
    so it is never written inside the source code. The three models used by
    this application are public, so the token is optional.
    """
    try:
        token = st.secrets.get("HF_TOKEN")
        if token:
            return token
    except Exception:
        # No secrets file is configured, which is perfectly fine.
        pass

    return os.environ.get("HF_TOKEN")


@st.cache_resource(show_spinner=False)
def load_models():
    """
    Load the three Hugging Face pipelines used by the application.

    The @st.cache_resource decorator makes Streamlit load the models only
    once. Every later rerun of the script reuses the same pipelines instead
    of downloading and building them again.

    Returns a dictionary with the three ready-to-use pipelines.
    """
    token = get_hf_token()
    device = 0 if torch.cuda.is_available() else -1

    image_model = pipeline(
        "image-to-text",
        model=IMAGE_MODEL,
        token=token,
        device=device,
    )

    story_model = pipeline(
        "text-generation",
        model=STORY_MODEL,
        token=token,
        device=device,
    )

    audio_model = pipeline(
        "text-to-speech",
        model=AUDIO_MODEL,
        token=token,
        device=device,
    )

    return {
        "image": image_model,
        "story": story_model,
        "audio": audio_model,
    }


# ---------------------------------------------------------------------------
# 2. Image to text
# ---------------------------------------------------------------------------

def image2text(image, model):
    """
    Describe the content of an image.

    Parameters
    ----------
    image : PIL.Image.Image
        The picture uploaded by the child.
    model : transformers pipeline
        The image-to-text pipeline used to analyse the picture.

    Returns the caption generated by the model.
    """
    result = model(
        image,
        max_new_tokens=MAX_CAPTION_TOKENS
    )

    caption = result[0]["generated_text"]

    return caption


# ---------------------------------------------------------------------------
# 3. Text to story
# ---------------------------------------------------------------------------

def text2story(caption, model):
    """
    Create a short children's story from an image description.

    Parameters
    ----------
    caption : str
        The image description produced by the image-to-text model.
    model : transformers pipeline
        The text-generation pipeline used to write the story.

    Returns a story of approximately 50-100 words for children aged 3-10.
    """
    messages = [
        {
            "role": "system",
            "content": (
                "You are a children's storyteller for children aged 3 to 10. "
                "Write short, complete, child-friendly stories. "
                "Each story must have a beginning, a small adventure, "
                "a resolution, and a happy ending. "
                "Write approximately 60 to 80 words and never more than 100 words. "
                "Avoid violence, frightening events, and adult themes. "
                "Output only the story itself. "
                "Never output instructions, labels, headings, explanations, or formatting."
            )
        },
        {
            "role": "user",
            "content": (
                f"Create a short story inspired by this image description: {caption}"
            )
        }
    ]

    result = model(
        messages,
        max_new_tokens=MAX_STORY_TOKENS
    )

    story = result[0]["generated_text"][-1]["content"].strip()

    return story


# ---------------------------------------------------------------------------
# 4. Text to audio
# ---------------------------------------------------------------------------

def text2audio(text, model):
    """
    Turn the story into spoken audio.

    Parameters
    ----------
    text : str
        The story to narrate.
    model : transformers pipeline
        The text-to-speech pipeline used to read the story out loud.

    Returns a tuple (audio waveform, sampling rate).
    """
    result = model(text)

    audio = result["audio"]
    sampling_rate = result["sampling_rate"]

    return audio, sampling_rate


def audio_to_wav_bytes(audio, sampling_rate):
    """
    Convert the waveform produced by text2audio() into playable WAV bytes.

    Streamlit needs a real audio file to play and to download, so the raw
    waveform is normalised and written into an in-memory WAV file.
    """
    waveform = np.squeeze(np.asarray(audio, dtype=np.float32))

    peak = float(np.max(np.abs(waveform))) if waveform.size else 0.0
    if peak > 0:
        waveform = waveform / peak * 0.95

    samples = (waveform * 32767).astype(np.int16)

    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(int(sampling_rate))
        wav_file.writeframes(samples.tobytes())

    return buffer.getvalue()


# ---------------------------------------------------------------------------
# 5. Interface helpers
# ---------------------------------------------------------------------------

def apply_styles():
    """Apply the playful storybook styling used across the application."""
    st.markdown(
        """
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Baloo+2:wght@600;800&family=Nunito:wght@400;600;700&display=swap');

        :root {
            --paper:   #fffaf2;
            --ink:     #3d2b56;
            --soft:    #7a6a8c;
            --grape:   #7b5ea7;
            --coral:   #ff7a7a;
            --sunny:   #ffc24b;
            --mint:    #63d0b4;
            --sky:     #8fd3ff;
        }

        .stApp {
            background:
                radial-gradient(circle at 12% 8%,  rgba(255,194,75,.20), transparent 42%),
                radial-gradient(circle at 88% 4%,  rgba(143,211,255,.28), transparent 40%),
                radial-gradient(circle at 78% 92%, rgba(99,208,180,.22), transparent 45%),
                var(--paper);
        }

        .block-container {
            max-width: 900px;
            padding-top: 2rem;
            padding-bottom: 4rem;
        }

        html, body, [class*="css"], .stMarkdown, .stApp {
            font-family: 'Nunito', 'Trebuchet MS', sans-serif;
            color: var(--ink);
        }

        /* ---------------- Header ---------------- */

        .hero {
            text-align: center;
            padding: 1.2rem 1rem 0.4rem;
        }

        .hero-emoji {
            font-size: 3.6rem;
            display: inline-block;
            animation: float 3.2s ease-in-out infinite;
        }

        .hero-emoji:nth-child(2) { animation-delay: .4s; }
        .hero-emoji:nth-child(3) { animation-delay: .8s; }

        @keyframes float {
            0%, 100% { transform: translateY(0) rotate(-3deg); }
            50%      { transform: translateY(-14px) rotate(3deg); }
        }

        .hero-title {
            font-family: 'Baloo 2', cursive;
            font-size: clamp(2.2rem, 7vw, 3.4rem);
            font-weight: 800;
            line-height: 1.1;
            margin: .3rem 0 .2rem;
            background: linear-gradient(90deg, var(--coral), var(--sunny), var(--mint), var(--grape));
            background-size: 300% 100%;
            -webkit-background-clip: text;
            background-clip: text;
            -webkit-text-fill-color: transparent;
            animation: shimmer 9s ease infinite;
        }

        @keyframes shimmer {
            0%, 100% { background-position: 0% 50%; }
            50%      { background-position: 100% 50%; }
        }

        .hero-subtitle {
            font-size: 1.15rem;
            font-weight: 600;
            color: var(--soft);
            margin-bottom: 1.4rem;
        }

        /* ---------------- Cards ---------------- */

        .card {
            background: #ffffff;
            border-radius: 28px;
            padding: 1.4rem 1.6rem;
            margin: 1rem 0;
            box-shadow: 0 10px 30px rgba(61, 43, 86, .10);
            border: 3px solid rgba(123, 94, 167, .10);
        }

        .step-list {
            display: flex;
            flex-wrap: wrap;
            gap: .9rem;
            justify-content: center;
        }

        .step {
            flex: 1 1 200px;
            background: #fff;
            border-radius: 22px;
            padding: 1rem .9rem;
            text-align: center;
            box-shadow: 0 8px 22px rgba(61, 43, 86, .09);
            border: 3px solid rgba(123, 94, 167, .10);
        }

        .step-emoji { font-size: 2rem; display: block; margin-bottom: .3rem; }
        .step-text  { font-weight: 700; font-size: 1rem; color: var(--ink); }

        .section-title {
            font-family: 'Baloo 2', cursive;
            font-size: 1.6rem;
            font-weight: 700;
            text-align: center;
            margin: 1.6rem 0 .6rem;
            color: var(--grape);
        }

        /* ---------------- Upload area ---------------- */

        [data-testid="stFileUploaderDropzone"] {
            background: #ffffff;
            border: 4px dashed var(--sky);
            border-radius: 26px;
            padding: 1.4rem;
            transition: all .25s ease;
        }

        [data-testid="stFileUploaderDropzone"]:hover {
            border-color: var(--mint);
            transform: translateY(-3px);
            box-shadow: 0 12px 26px rgba(61, 43, 86, .12);
        }

        [data-testid="stFileUploaderDropzone"] * { color: var(--soft) !important; }

        [data-testid="stFileUploaderDropzone"] button {
            background: var(--sky) !important;
            color: #17324a !important;
            border: none !important;
            border-radius: 999px !important;
            font-weight: 700 !important;
        }

        /* ---------------- Picture preview ---------------- */

        .frame-caption {
            text-align: center;
            font-weight: 700;
            color: var(--soft);
            margin-top: .4rem;
        }

        [data-testid="stImage"] img {
            border-radius: 24px;
            border: 6px solid #ffffff;
            box-shadow: 0 14px 34px rgba(61, 43, 86, .18);
        }

        /* ---------------- Buttons ---------------- */

        .stButton > button {
            width: 100%;
            font-family: 'Baloo 2', cursive;
            font-size: 1.35rem !important;
            font-weight: 800;
            color: #ffffff !important;
            background: linear-gradient(135deg, var(--coral), var(--sunny));
            border: none;
            border-radius: 999px;
            padding: .85rem 1.2rem;
            box-shadow: 0 10px 24px rgba(255, 122, 122, .40);
            transition: transform .18s ease, box-shadow .18s ease;
            animation: pulse 2.6s ease-in-out infinite;
        }

        .stButton > button:hover {
            transform: translateY(-3px) scale(1.02);
            box-shadow: 0 16px 30px rgba(255, 122, 122, .50);
            color: #ffffff !important;
        }

        .stButton > button:active { transform: translateY(0) scale(.99); }

        @keyframes pulse {
            0%, 100% { box-shadow: 0 10px 24px rgba(255, 122, 122, .40); }
            50%      { box-shadow: 0 10px 34px rgba(255, 194, 75, .55); }
        }

        .stDownloadButton > button {
            width: 100%;
            font-family: 'Baloo 2', cursive;
            font-size: 1.05rem !important;
            font-weight: 700;
            color: #17324a !important;
            background: var(--mint);
            border: none;
            border-radius: 999px;
            padding: .6rem 1rem;
        }

        /* ---------------- Magic progress ---------------- */

        .magic-step {
            text-align: center;
            background: #ffffff;
            border-radius: 26px;
            padding: 1.3rem;
            margin: .8rem 0;
            box-shadow: 0 10px 28px rgba(61, 43, 86, .12);
            border: 3px solid rgba(143, 211, 255, .40);
        }

        .magic-emoji {
            font-size: 3rem;
            display: block;
            animation: bounce 1.1s ease-in-out infinite;
        }

        @keyframes bounce {
            0%, 100% { transform: translateY(0) scale(1); }
            50%      { transform: translateY(-12px) scale(1.08); }
        }

        .magic-text {
            font-family: 'Baloo 2', cursive;
            font-size: 1.45rem;
            font-weight: 700;
            color: var(--grape);
            margin-top: .4rem;
        }

        .stProgress > div > div > div > div {
            background: linear-gradient(90deg, var(--coral), var(--sunny), var(--mint));
            border-radius: 999px;
        }

        /* ---------------- Story card ---------------- */

        .story-card {
            position: relative;
            background: linear-gradient(160deg, #fffdf8, #fff4e3);
            border-radius: 32px;
            padding: 2.1rem 2rem 1.8rem;
            margin: .6rem 0 1.2rem;
            border: 4px solid var(--sunny);
            box-shadow: 0 16px 40px rgba(61, 43, 86, .16);
            animation: appear .7s ease both;
        }

        @keyframes appear {
            from { opacity: 0; transform: translateY(24px) scale(.97); }
            to   { opacity: 1; transform: translateY(0) scale(1); }
        }

        .story-title {
            font-family: 'Baloo 2', cursive;
            font-size: 1.9rem;
            font-weight: 800;
            color: var(--grape);
            text-align: center;
            margin-bottom: .9rem;
        }

        .story-text {
            font-size: 1.28rem;
            line-height: 2.05rem;
            font-weight: 600;
            color: var(--ink);
            white-space: pre-wrap;
        }

        .story-text::first-letter {
            font-family: 'Baloo 2', cursive;
            font-size: 3.4rem;
            font-weight: 800;
            color: var(--coral);
            float: left;
            line-height: 1;
            margin: .1rem .85rem .1rem 0;
            padding: 0;
        }

        .story-end {
            text-align: center;
            font-family: 'Baloo 2', cursive;
            font-size: 1.25rem;
            color: var(--soft);
            margin-top: 1.2rem;
        }

        /* ---------------- Audio ---------------- */

        .audio-card {
            background: linear-gradient(135deg, #eef8ff, #e7fff7);
            border-radius: 28px;
            padding: 1.3rem 1.5rem .9rem;
            border: 4px solid var(--sky);
            box-shadow: 0 12px 30px rgba(61, 43, 86, .12);
            text-align: center;
        }

        .audio-title {
            font-family: 'Baloo 2', cursive;
            font-size: 1.45rem;
            font-weight: 700;
            color: var(--grape);
        }

        .audio-hint { font-weight: 600; color: var(--soft); margin-bottom: .4rem; }

        [data-testid="stAudio"] audio { width: 100%; border-radius: 999px; }

        /* ---------------- Friendly messages ---------------- */

        .friendly-note {
            background: #fff3f3;
            border: 3px solid var(--coral);
            border-radius: 24px;
            padding: 1.1rem 1.3rem;
            text-align: center;
            font-size: 1.12rem;
            font-weight: 700;
            color: #8c3a4a;
            margin: .8rem 0;
        }

        .friendly-tip {
            background: #f3f7ff;
            border: 3px dashed var(--grape);
            border-radius: 24px;
            padding: 1rem 1.2rem;
            text-align: center;
            font-size: 1.1rem;
            font-weight: 700;
            color: var(--grape);
            margin: .8rem 0;
        }

        .footer-note {
            text-align: center;
            color: var(--soft);
            font-weight: 600;
            margin-top: 2.2rem;
        }

        /* Hide Streamlit chrome so the page feels like a storybook. */
        #MainMenu, footer, [data-testid="stHeader"] { visibility: hidden; }

        @media (max-width: 640px) {
            .story-card { padding: 1.5rem 1.2rem; }
            .story-text { font-size: 1.15rem; line-height: 1.9rem; }
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def render_header():
    """Draw the welcome area and the simple instructions for the child."""
    st.markdown(
        """
        <div class="hero">
            <span class="hero-emoji">🎈</span>
            <span class="hero-emoji">📖</span>
            <span class="hero-emoji">✨</span>
            <div class="hero-title">Magic Story Maker</div>
            <div class="hero-subtitle">Give me a picture and I will invent a story just for you!</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <div class="step-list">
            <div class="step">
                <span class="step-emoji">🖼️</span>
                <span class="step-text">1. Choose a picture</span>
            </div>
            <div class="step">
                <span class="step-emoji">🪄</span>
                <span class="step-text">2. Press the magic button</span>
            </div>
            <div class="step">
                <span class="step-emoji">🎧</span>
                <span class="step-text">3. Listen to your story</span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_message(text, kind="tip"):
    """Show a friendly message instead of a technical error."""
    css_class = "friendly-note" if kind == "note" else "friendly-tip"
    st.markdown(f'<div class="{css_class}">{text}</div>', unsafe_allow_html=True)


def render_progress(placeholder, progress_bar, emoji, message, percent):
    """Show one child-friendly step of the magic while the models work."""
    placeholder.markdown(
        f"""
        <div class="magic-step">
            <span class="magic-emoji">{emoji}</span>
            <div class="magic-text">{message}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    progress_bar.progress(percent)


def render_story(story):
    """Show the finished story inside a storybook page."""
    safe_story = html.escape(story)
    st.markdown(
        f"""
        <div class="story-card">
            <div class="story-title">🌟 Your Story 🌟</div>
            <div class="story-text">{safe_story}</div>
            <div class="story-end">～ The End ～</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_audio(audio_bytes):
    """Show the narration section so the child can listen to the story."""
    st.markdown(
        """
        <div class="audio-card">
            <div class="audio-title">🎧 Listen to your story</div>
            <div class="audio-hint">Press play and I will read it to you!</div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.audio(audio_bytes, format="audio/wav")


def reset_story():
    """Forget the current story so the child can start a new adventure."""
    st.session_state.pop("story", None)
    st.session_state.pop("audio_bytes", None)


# ---------------------------------------------------------------------------
# 6. Main application
# ---------------------------------------------------------------------------

def main():
    """
    Run the complete storytelling application.

    main() is the orchestrator: it prepares the page, collects the picture
    from the child, calls the three AI stages in order, and presents the
    story and its narration.
    """
    # --- Page setup ------------------------------------------------------
    st.set_page_config(
        page_title="Magic Story Maker",
        page_icon="🎈",
        layout="centered",
    )
    apply_styles()
    render_header()

    # --- Step 1: the child chooses a picture -----------------------------
    st.markdown('<div class="section-title">🖼️ Choose your picture</div>', unsafe_allow_html=True)

    uploaded_file = st.file_uploader(
        "Pick a happy picture from your computer",
        type=ACCEPTED_IMAGE_TYPES,
        on_change=reset_story,
    )

    if uploaded_file is None:
        render_message("👆 Choose a picture and the magic will begin!")
        st.markdown(
            '<div class="footer-note">Made with ✨ for young storytellers</div>',
            unsafe_allow_html=True,
        )
        return

    # --- Step 2: open and preview the picture ----------------------------
    try:
        image = Image.open(uploaded_file).convert("RGB")
    except (UnidentifiedImageError, OSError, ValueError):
        render_message(
            "😅 Oh no! I could not open that picture. Please try a different one.",
            kind="note",
        )
        return

    left, middle, right = st.columns([1, 3, 1])
    with middle:
        st.image(image, use_container_width=True)
        st.markdown(
            '<div class="frame-caption">What a lovely picture! 💛</div>',
            unsafe_allow_html=True,
        )

    # --- Step 3: the magic button ----------------------------------------
    st.markdown('<div class="section-title">🪄 Ready for the magic?</div>', unsafe_allow_html=True)
    create_story = st.button("✨ Create my story! ✨")

    if create_story:
        reset_story()

        progress_placeholder = st.empty()
        progress_bar = st.progress(0)

        # Wake the models up (only the very first time).
        render_progress(progress_placeholder, progress_bar, "🌙", "Waking up the story elves...", 5)
        try:
            models = load_models()
        except Exception:
            progress_placeholder.empty()
            progress_bar.empty()
            render_message(
                "😴 The story elves are still sleeping. Please try again in a moment!",
                kind="note",
            )
            return

        # Stage 1 - look at the picture.
        render_progress(progress_placeholder, progress_bar, "👀", "Looking at your picture...", 25)
        try:
            caption = image2text(image, models["image"])
        except Exception:
            progress_placeholder.empty()
            progress_bar.empty()
            render_message(
                "🙈 I could not see that picture very well. Let's try another one!",
                kind="note",
            )
            return

        if not caption or not caption.strip():
            progress_placeholder.empty()
            progress_bar.empty()
            render_message(
                "🙈 That picture is a little too mysterious for me. Try another one!",
                kind="note",
            )
            return

        # Stage 2 - imagine the story.
        render_progress(progress_placeholder, progress_bar, "💭", "Imagining your adventure...", 55)
        try:
            story = text2story(caption, models["story"])
        except Exception:
            progress_placeholder.empty()
            progress_bar.empty()
            render_message(
                "💤 My imagination got sleepy. Please press the magic button again!",
                kind="note",
            )
            return

        if not story or not story.strip():
            progress_placeholder.empty()
            progress_bar.empty()
            render_message(
                "💤 My imagination got sleepy. Please press the magic button again!",
                kind="note",
            )
            return

        st.session_state["story"] = story

        # Stage 3 - read the story out loud.
        render_progress(progress_placeholder, progress_bar, "🎙️", "Giving your story a voice...", 80)
        try:
            audio, sampling_rate = text2audio(story, models["audio"])
            st.session_state["audio_bytes"] = audio_to_wav_bytes(audio, sampling_rate)
        except Exception:
            # The story is still perfectly readable without narration.
            st.session_state["audio_bytes"] = None

        render_progress(progress_placeholder, progress_bar, "🎉", "Your story is ready!", 100)
        progress_placeholder.empty()
        progress_bar.empty()

        st.balloons()

    # --- Step 4: show the finished story ---------------------------------
    if "story" in st.session_state:
        render_story(st.session_state["story"])

        audio_bytes = st.session_state.get("audio_bytes")
        if audio_bytes:
            render_audio(audio_bytes)
            st.download_button(
                "💾 Save my story audio",
                data=audio_bytes,
                file_name="my_story.wav",
                mime="audio/wav",
            )
        else:
            render_message("🤫 My voice is a little quiet today, but you can still read your story!")

        st.markdown(
            '<div class="section-title">🌈 Want another adventure?</div>',
            unsafe_allow_html=True,
        )
        if st.button("🔄 Make a new story"):
            reset_story()
            st.rerun()

    st.markdown(
        '<div class="footer-note">Made with ✨ for young storytellers</div>',
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
